<a href="https://colab.research.google.com/github/brunobobadilla06/Bruno-CienciaDeDatos/blob/main/Filtros_y_GroupBy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
# URL del archivo CSV
url = 'https://raw.githubusercontent.com/brunobobadilla06/Bruno-CienciaDeDatos/refs/heads/main/stocks_data.csv'
df_stockdata = pd.read_csv(url)
print(df_stockdata)
df_stockdata.head()

   formatted_date          MCD         SBUX         GOOG         AMZN  \
0      2016-01-01  1142.384153  2853.621490  2204.022007  1808.015698
1      2016-02-01   570.020153   574.711394   933.599462  1588.526602
2      2016-03-01  1789.471270   167.957726  1834.408210   536.456647
3      2016-04-01   132.133908  2730.681594   798.576545  1997.691185
4      2016-05-01   292.822731   612.069101   164.325048   996.231082
..            ...          ...          ...          ...          ...
66     2021-07-01  1292.884108    96.733846   827.971757  1638.653618
67     2021-08-01   379.720716  1742.253932   843.944005  1675.908667
68     2021-09-01   550.852698  2745.803479  1273.748459  1167.921429
69     2021-10-01  2165.566338   912.451495  1712.221782  1443.869695
70     2021-11-01  1022.704356  2319.609245   346.596812   253.159212

           MSFT          JPM          BAC            C          MAR  \
0    493.375362   493.303725   202.508328  2602.543153  1815.311585
1   1312.876705   894.950546  1847.203097   444.296766   897.669606
2    223.203231  2848.190046  2897.927138  2430.940124   934.702894
3    955.781896  1574.602023  1653.729530   579.017733  2909.666344
4   1184.371550   835.906624  2491.350402  1089.557380   864.375494
..          ...          ...          ...          ...          ...
66  1911.430313   795.926426   443.887540  2509.742803  2953.674477
67  1964.718553  2494.333157   643.071177    62.657611   436.550321
68  1571.185585   169.488921   523.861605  2221.959841   275.912044
69  2001.103361  2812.384326  2205.739129   668.372924   122.613911
70  2192.720606  1501.609209  2074.555117  1321.437196   761.814039

            HLT          RCL            V           MA         PYPL
0   2132.975556    91.135948  2910.632261  2502.354643   660.647159
1   1118.094675  1384.527853  2361.972605   623.031133  1557.276282
2    320.086179  2062.172089  1337.252906   392.453557  1500.675423
3   2332.144485  2820.311856  2687.637231  1805.762937  2767.966478
4   1641.807367   448.544948  2412.525033   251.415412  2961.054202
..          ...          ...          ...          ...          ...
66  1591.299841   539.887479   838.752760    84.620309  2745.467455
67  2703.055366  2625.453530  1804.316913  1813.535075  2005.158923
68  1821.361765   758.686856  1186.207974   887.420398  1086.347968
69   808.924212  1797.381454   182.734666  1504.207754  1802.623261
70  2462.733883  2404.265161  2093.248518   838.271058  1782.985081

[71 rows x 15 columns]

,formatted_date,MCD,SBUX,GOOG,AMZN,MSFT,JPM,BAC,C,MAR,HLT,RCL,V,MA,PYPL
0,2016-01-01,1142.384153,2853.621490,2204.022007,1808.015698,493.375362,493.303725,202.508328,2602.543153,1815.311585,2132.975556,91.135948,2910.632261,2502.354643,660.647159
1,2016-02-01,570.020153,574.711394,933.599462,1588.526602,1312.876705,894.950546,1847.203097,444.296766,897.669606,1118.094675,1384.527853,2361.972605,623.031133,1557.276282
2,2016-03-01,1789.471270,167.957726,1834.408210,536.456647,223.203231,2848.190046,2897.927138,2430.940124,934.702894,320.086179,2062.172089,1337.252906,392.453557,1500.675423
3,2016-04-01,132.133908,2730.681594,798.576545,1997.691185,955.781896,1574.602023,1653.729530,579.017733,2909.666344,2332.144485,2820.311856,2687.637231,1805.762937,2767.966478
4,2016-05-01,292.822731,612.069101,164.325048,996.231082,1184.371550,835.906624,2491.350402,1089.557380,864.375494,1641.807367,448.544948,2412.525033,251.415412,2961.054202

In [2]:
# Mostrar informacion general del DatFrame
df_stockdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   formatted_date  71 non-null     object
 1   MCD             71 non-null     float64
 2   SBUX            71 non-null     float64
 3   GOOG            71 non-null     float64
 4   AMZN            71 non-null     float64
 5   MSFT            71 non-null     float64
 6   JPM             71 non-null     float64
 7   BAC             71 non-null     float64
 8   C               71 non-null     float64
 9   MAR             71 non-null     float64
 10  HLT             71 non-null     float64
 11  RCL             71 non-null     float64
 12  V               71 non-null     float64
 13  MA              71 non-null     float64
 14  PYPL            71 non-null     float64
dtypes: float64(14), object(1)
memory usage: 8.4+ KB

In [3]:
# Es buena practica convertir la columna Date a tipo datetime
#  Si Date no es de tipo datetime, muchas operaciones de tiempo fallaran o seran ineficientes
df_stockdata['formatted_date'] = pd.to_datetime(df_stockdata['formatted_date'])
df_stockdata.info()

#  Saber el tipo de datos
df_stockdata.dtypes['formatted_date']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   formatted_date  71 non-null     datetime64[ns]
 1   MCD             71 non-null     float64
 2   SBUX            71 non-null     float64
 3   GOOG            71 non-null     float64
 4   AMZN            71 non-null     float64
 5   MSFT            71 non-null     float64
 6   JPM             71 non-null     float64
 7   BAC             71 non-null     float64
 8   C               71 non-null     float64
 9   MAR             71 non-null     float64
 10  HLT             71 non-null     float64
 11  RCL             71 non-null     float64
 12  V               71 non-null     float64
 13  MA              71 non-null     float64
 14  PYPL            71 non-null     float64
dtypes: datetime64[ns](1), float64(14)
memory usage: 8.4 KB

dtype('<M8[ns]')

In [4]:
# VER LAS DIMENSIONES DEL DATAFRAME(FILAS, COLUMNAS)
print(f"\nDimensiones del data Frame: {df_stockdata.shape}")

Dimensiones del data Frame: (71, 15)

In [5]:
# Ver las columnas
print(f"\nColumnas del data Frame: {df_stockdata.columns.to_list()}")

Columnas del data Frame: ['formatted_date', 'MCD', 'SBUX', 'GOOG', 'AMZN', 'MSFT', 'JPM', 'BAC', 'C', 'MAR', 'HLT', 'RCL', 'V', 'MA', 'PYPL']

In [7]:
# Filtrado con indices booleanos
import pandas as pd
# URL del archivo CSV
url = 'https://raw.githubusercontent.com/brunobobadilla06/Bruno-CienciaDeDatos/refs/heads/main/stocks_data.csv'
df_stockdata = pd.read_csv(url)

df_stockdata['formatted_date'] = pd.to_datetime(df_stockdata['formatted_date'])
condicion_fecha = df_stockdata['formatted_date'] >= pd.Timestamp('2016-03-01')
df_desde_marzo = df_stockdata[condicion_fecha]
print(df_desde_marzo)


#Filtrado por fecha
condicion_fecha = df_stockdata['formatted_date'] >= pd.Timestamp('2016-03-01')
def_desde_marzo = df_stockdata[condicion_fecha]

   formatted_date          MCD         SBUX         GOOG         AMZN  \
2      2016-03-01  1789.471270   167.957726  1834.408210   536.456647
3      2016-04-01   132.133908  2730.681594   798.576545  1997.691185
4      2016-05-01   292.822731   612.069101   164.325048   996.231082
5      2016-06-01  2323.566965   620.185574    46.400688  2451.920443
6      2016-07-01   953.617495   995.794466  2196.930350  1923.545690
..            ...          ...          ...          ...          ...
66     2021-07-01  1292.884108    96.733846   827.971757  1638.653618
67     2021-08-01   379.720716  1742.253932   843.944005  1675.908667
68     2021-09-01   550.852698  2745.803479  1273.748459  1167.921429
69     2021-10-01  2165.566338   912.451495  1712.221782  1443.869695
70     2021-11-01  1022.704356  2319.609245   346.596812   253.159212

           MSFT          JPM          BAC            C          MAR  \
2    223.203231  2848.190046  2897.927138  2430.940124   934.702894
3    955.781896  1574.602023  1653.729530   579.017733  2909.666344
4   1184.371550   835.906624  2491.350402  1089.557380   864.375494
5   2129.366311  2195.151289  2320.672930   249.912616  1094.643214
6   2665.021845  1432.478328   385.194910  2148.337018  2289.531594
..          ...          ...          ...          ...          ...
66  1911.430313   795.926426   443.887540  2509.742803  2953.674477
67  1964.718553  2494.333157   643.071177    62.657611   436.550321
68  1571.185585   169.488921   523.861605  2221.959841   275.912044
69  2001.103361  2812.384326  2205.739129   668.372924   122.613911
70  2192.720606  1501.609209  2074.555117  1321.437196   761.814039

            HLT          RCL            V           MA         PYPL
2    320.086179  2062.172089  1337.252906   392.453557  1500.675423
3   2332.144485  2820.311856  2687.637231  1805.762937  2767.966478
4   1641.807367   448.544948  2412.525033   251.415412  2961.054202
5    374.131107  2593.417175  1881.195437  1012.767134   218.768300
6   1696.993277  2319.772524  1496.572921  1582.516503  1299.796825
..          ...          ...          ...          ...          ...
66  1591.299841   539.887479   838.752760    84.620309  2745.467455
67  2703.055366  2625.453530  1804.316913  1813.535075  2005.158923
68  1821.361765   758.686856  1186.207974   887.420398  1086.347968
69   808.924212  1797.381454   182.734666  1504.207754  1802.623261
70  2462.733883  2404.265161  2093.248518   838.271058  1782.985081

[69 rows x 15 columns]

In [9]:
# Filtrar por tickets especificos
condicion_goog_alto = df_stockdata['GOOG'] > 2500
df_goog_alto = df_stockdata[condicion_goog_alto]
print(df_goog_alto)

   formatted_date          MCD         SBUX         GOOG         AMZN  \
14     2017-03-01  2186.088366  2694.417472  2664.646680  2346.230371
16     2017-05-01   817.651032   754.649241  2919.841348  1197.500242
17     2017-06-01  1947.052719   556.018718  2823.161996  2863.167874
23     2017-12-01  1990.786209   861.403674  2865.949884  2221.553843
26     2018-03-01  2826.150482  1176.724834  2884.735975  2718.891407
29     2018-06-01  1185.928986    62.187825  2718.984470   301.121430
33     2018-10-01  2245.753291  1762.605232  2887.652469  1143.365621
34     2018-11-01   249.175797  1674.947225  2908.828531  1583.600597
36     2019-01-01  2063.651582   512.972310  2735.453738  2472.935611
54     2020-07-01  1871.616085  1614.379443  2684.860972  2372.133717
58     2020-11-01   400.248163  2764.900391  2613.592195  1570.949030

           MSFT          JPM          BAC            C          MAR  \
14  1936.833989   279.895696   510.037281  2698.705940  1831.094307
16  2679.378269  1904.481719  2390.589572  1522.832167  1743.404537
17  2747.147239  1129.371340    75.906151  2787.106131  1301.706921
23  1676.431536  1846.810616  1276.212185   765.761039  1087.238856
26   611.499670   236.003064   329.310664    84.118822   310.495593
29   978.361504  2851.684042  2853.303226  1733.110528  1906.556520
33   878.564896  2609.739411   694.079640  2890.770942    66.098790
34  1899.313955  2096.373606  1379.986962  1893.847498  1765.413506
36  2850.905742  2185.386940  1851.843132  1272.181818  2800.203596
54   480.474393   955.814541   768.012745  2239.520489   129.591331
58  1786.088044  1215.038030   192.642067  1025.535808  2414.474742

            HLT          RCL            V           MA         PYPL
14    57.315243   331.370482  2000.600254    45.032904   507.599913
16  1492.777551   609.871674  2175.682782   863.893916   102.218420
17  2900.964813  2891.951332  2563.438083   904.513209  1173.740254
23  2280.802948    72.748661   374.735742   166.627847   150.964543
26  2058.530117   241.430286   977.357622  2539.279674    99.117649
29  1361.883200   900.835992  1006.133700  2027.379815  2264.552352
33  2910.540115   158.184938  2676.695048  1597.272294  2979.105444
34  2706.439291   164.975750   864.460673  2852.722108  2674.083438
36  2602.209752   164.299450   108.309914  1148.096200  2437.343392
54  1722.572364  2294.502297  2633.993941  1045.982794  2469.134195
58    43.757108  1020.492540  1212.561020  1626.064941  2761.971181

In [14]:
import pandas as pd
# URL del archivo CSV
url = 'https://raw.githubusercontent.com/brunobobadilla06/Bruno-CienciaDeDatos/refs/heads/main/stocks_data.csv'
df_stockdata = pd.read_csv(url)

df_stockdata['formatted_date'] = pd.to_datetime(df_stockdata['formatted_date'])
condicion_fecha = df_stockdata['formatted_date'] >= pd.Timestamp('2016-03-01')
df_desde_marzo = df_stockdata[condicion_fecha]


# Codicion multiple
df_combo1 = df_stockdata[(df_stockdata['GOOG'] > 700) & (df_stockdata['MSFT'] < 1000)]
print(df_combo1)

   formatted_date          MCD         SBUX         GOOG         AMZN  \
0      2016-01-01  1142.384153  2853.621490  2204.022007  1808.015698
2      2016-03-01  1789.471270   167.957726  1834.408210   536.456647
3      2016-04-01   132.133908  2730.681594   798.576545  1997.691185
10     2016-11-01  2888.468466   777.793419  1506.828063   923.608580
11     2016-12-01  2957.381849   748.904156  2026.242576  2292.010258
22     2017-11-01  2391.702998   834.371786  1333.745119   263.015453
25     2018-02-01  1524.314688  2573.774828  1986.320086   513.915248
26     2018-03-01  2826.150482  1176.724834  2884.735975  2718.891407
29     2018-06-01  1185.928986    62.187825  2718.984470   301.121430
33     2018-10-01  2245.753291  1762.605232  2887.652469  1143.365621
44     2019-09-01   211.401541   852.326615  2424.417801  2252.331280
45     2019-10-01  2148.648270  2688.764308  1549.682003  1610.377051
48     2020-01-01   268.294225  1587.798827  1248.878576  2947.664492
49     2020-02-01  1727.689688   861.537908  2315.394012   585.519933
50     2020-03-01  1611.790615   183.915904  1029.714706   429.211591
51     2020-04-01  1066.138752  2790.701558  2496.939641  2896.129925
54     2020-07-01  1871.616085  1614.379443  2684.860972  2372.133717
59     2020-12-01  1058.647603  1060.451010  2220.378707  1373.087284

          MSFT          JPM          BAC            C          MAR  \
0   493.375362   493.303725   202.508328  2602.543153  1815.311585
2   223.203231  2848.190046  2897.927138  2430.940124   934.702894
3   955.781896  1574.602023  1653.729530   579.017733  2909.666344
10  875.976268   139.554234  1840.406072  1522.956699   182.891891
11  735.783506  2192.802555  1122.315904  1907.948317  1911.583241
22  105.291708  2889.065792  2512.860958  2097.043392  1244.590245
25  239.589180  1937.985256   108.738592  1769.753476  2822.483817
26  611.499670   236.003064   329.310664    84.118822   310.495593
29  978.361504  2851.684042  2853.303226  1733.110528  1906.556520
33  878.564896  2609.739411   694.079640  2890.770942    66.098790
44  578.027427   651.767490  1130.302145  1469.033266  1866.216671
45  348.300874  1358.814729  1611.873281   750.137396   829.652396
48  362.755539  1211.631129  2909.327187  2600.556164  2456.704051
49  991.327332  1293.546223  1537.602825   749.956905   371.065369
50  218.223662  2970.181890   987.390920  2435.327104   786.282745
51  399.162754  2200.676401  2816.871157   568.262207   227.493914
54  480.474393   955.814541   768.012745  2239.520489   129.591331
59  697.076324  1373.745363   448.345351   553.869350  1510.152285

            HLT          RCL            V           MA         PYPL
0   2132.975556    91.135948  2910.632261  2502.354643   660.647159
2    320.086179  2062.172089  1337.252906   392.453557  1500.675423
3   2332.144485  2820.311856  2687.637231  1805.762937  2767.966478
10   857.579999  2727.549681   741.498815   460.337770  1483.674698
11  1621.250812   298.160617  2510.848412   982.716793   583.959976
22   544.684131   494.618017   773.221408  1661.203194  2152.349890
25  1739.158308  1182.864681  1940.566009  1391.011085  1650.481864
26  2058.530117   241.430286   977.357622  2539.279674    99.117649
29  1361.883200   900.835992  1006.133700  2027.379815  2264.552352
33  2910.540115   158.184938  2676.695048  1597.272294  2979.105444
44  1125.673510  1403.728107  2249.988686   138.949113   779.737725
45  1150.533964    89.611457   986.575122   658.000581  1002.667136
48   795.971396   537.536135  2015.870363  2790.246688  1683.585792
49  1843.541526   887.232743  1756.277518   488.457264  1458.986103
50  2054.063085  2287.876744  1799.047060  1430.581280  1253.167515
51  2231.128328  1736.185146  2530.231467   445.123959  2391.943916
54  1722.572364  2294.502297  2633.993941  1045.982794  2469.134195
59  1274.208585  2747.092326  1106.309880  1754.347400  1907.824935

In [15]:
condicion_marzo = df_stockdata['formatted_date'] >= '2016-03-01'
condicion_amazon_alto = df_stockdata['AMZN'] > 2500
df_combo2 = df_stockdata[condicion_marzo | condicion_amazon_alto]
print(df_combo2)

   formatted_date          MCD         SBUX         GOOG         AMZN  \
2      2016-03-01  1789.471270   167.957726  1834.408210   536.456647
3      2016-04-01   132.133908  2730.681594   798.576545  1997.691185
4      2016-05-01   292.822731   612.069101   164.325048   996.231082
5      2016-06-01  2323.566965   620.185574    46.400688  2451.920443
6      2016-07-01   953.617495   995.794466  2196.930350  1923.545690
..            ...          ...          ...          ...          ...
66     2021-07-01  1292.884108    96.733846   827.971757  1638.653618
67     2021-08-01   379.720716  1742.253932   843.944005  1675.908667
68     2021-09-01   550.852698  2745.803479  1273.748459  1167.921429
69     2021-10-01  2165.566338   912.451495  1712.221782  1443.869695
70     2021-11-01  1022.704356  2319.609245   346.596812   253.159212

           MSFT          JPM          BAC            C          MAR  \
2    223.203231  2848.190046  2897.927138  2430.940124   934.702894
3    955.781896  1574.602023  1653.729530   579.017733  2909.666344
4   1184.371550   835.906624  2491.350402  1089.557380   864.375494
5   2129.366311  2195.151289  2320.672930   249.912616  1094.643214
6   2665.021845  1432.478328   385.194910  2148.337018  2289.531594
..          ...          ...          ...          ...          ...
66  1911.430313   795.926426   443.887540  2509.742803  2953.674477
67  1964.718553  2494.333157   643.071177    62.657611   436.550321
68  1571.185585   169.488921   523.861605  2221.959841   275.912044
69  2001.103361  2812.384326  2205.739129   668.372924   122.613911
70  2192.720606  1501.609209  2074.555117  1321.437196   761.814039

            HLT          RCL            V           MA         PYPL
2    320.086179  2062.172089  1337.252906   392.453557  1500.675423
3   2332.144485  2820.311856  2687.637231  1805.762937  2767.966478
4   1641.807367   448.544948  2412.525033   251.415412  2961.054202
5    374.131107  2593.417175  1881.195437  1012.767134   218.768300
6   1696.993277  2319.772524  1496.572921  1582.516503  1299.796825
..          ...          ...          ...          ...          ...
66  1591.299841   539.887479   838.752760    84.620309  2745.467455
67  2703.055366  2625.453530  1804.316913  1813.535075  2005.158923
68  1821.361765   758.686856  1186.207974   887.420398  1086.347968
69   808.924212  1797.381454   182.734666  1504.207754  1802.623261
70  2462.733883  2404.265161  2093.248518   838.271058  1782.985081

[69 rows x 15 columns]

In [16]:
# Agrupacion con groupby()
# Necesitamos extraer componentes de la fecha (Año, Mes, Trimestre) para agrupar
df_stockdata['year'] = df_stockdata['formatted_date'].dt.year
df_stockdata['month'] = df_stockdata['formatted_date'].dt.month
df_stockdata['quarter'] = df_stockdata['formatted_date'].dt.quarter

df_stockdata.head(10)

,formatted_date,MCD,SBUX,GOOG,AMZN,MSFT,JPM,BAC,C,MAR,HLT,RCL,V,MA,PYPL,year,month,quarter
0,2016-01-01,1142.384153,2853.621490,2204.022007,1808.015698,493.375362,493.303725,202.508328,2602.543153,1815.311585,2132.975556,91.135948,2910.632261,2502.354643,660.647159,2016,1,1
1,2016-02-01,570.020153,574.711394,933.599462,1588.526602,1312.876705,894.950546,1847.203097,444.296766,897.669606,1118.094675,1384.527853,2361.972605,623.031133,1557.276282,2016,2,1
2,2016-03-01,1789.471270,167.957726,1834.408210,536.456647,223.203231,2848.190046,2897.927138,2430.940124,934.702894,320.086179,2062.172089,1337.252906,392.453557,1500.675423,2016,3,1
3,2016-04-01,132.133908,2730.681594,798.576545,1997.691185,955.781896,1574.602023,1653.729530,579.017733,2909.666344,2332.144485,2820.311856,2687.637231,1805.762937,2767.966478,2016,4,2
4,2016-05-01,292.822731,612.069101,164.325048,996.231082,1184.371550,835.906624,2491.350402,1089.557380,864.375494,1641.807367,448.544948,2412.525033,251.415412,2961.054202,2016,5,2
5,2016-06-01,2323.566965,620.185574,46.400688,2451.920443,2129.366311,2195.151289,2320.672930,249.912616,1094.643214,374.131107,2593.417175,1881.195437,1012.767134,218.768300,2016,6,2
6,2016-07-01,953.617495,995.794466,2196.930350,1923.545690,2665.021845,1432.478328,385.194910,2148.337018,2289.531594,1696.993277,2319.772524,1496.572921,1582.516503,1299.796825,2016,7,3
7,2016-08-01,105.494806,350.437538,123.344681,1920.138921,963.637264,1540.454953,2725.472428,770.397921,1248.837281,2273.986881,709.530552,258.630332,890.561815,508.827223,2016,8,3
8,2016-09-01,2791.202027,2430.117527,1911.209157,2618.237953,2416.906068,584.113075,2680.900226,1631.846458,2428.097261,2691.391161,974.470321,356.854216,706.967433,1298.510132,2016,9,3
9,2016-10-01,2459.503855,2586.369832,50.647828,1546.919489,1269.710679,689.660197,386.000141,1032.717059,2830.441821,989.912708,1570.808147,2117.966308,1109.979919,2916.192786,2016,10,4

In [20]:
ticker_cols = ['MCD', 'SBUX', 'GOOG', 'AMZN', 'MSFT', 'JPM', 'BAC', 'C', 'MAR', 'HLT', 'RCL', 'V', 'MA', 'PYPL']

# CALCULAR EL PRECIO PROMEDIO ANUAL PARA CADA TICKETS
# Agrupamos por año, y luego calculamos la media de todas las columnas numericas
promedio_anual = df_stockdata.groupby('year')[ticker_cols].mean()
promedio_anual.head()

,MCD,SBUX,GOOG,AMZN,MSFT,JPM,BAC,C,MAR,HLT,RCL,V,MA,PYPL
year,,,,,,,,,,,,,,
2016,1533.838973,1287.386985,1149.711218,1716.941879,1268.834224,1285.097300,1712.806759,1367.539270,1617.312686,1504.196184,1500.033476,1756.132206,1026.738754,1479.779124
2017,1804.930096,1492.415311,1875.463930,1268.562370,2014.165032,1343.280802,1436.322995,1643.784516,1456.501425,1824.998160,1421.171947,1546.111674,1234.712169,1112.974309
2018,1614.790399,1600.832842,1665.574214,1476.804462,1300.040587,1736.936332,1177.508790,1813.186731,1207.500218,1816.055636,1129.492182,1640.062840,1804.624401,1875.359713
2019,1562.967591,1410.188407,1417.195157,1987.548970,1566.252782,1420.429739,1464.899190,1410.024538,1763.043543,1378.920654,904.334448,1074.505580,1213.750519,1658.291227
2020,1159.219380,1745.392282,1679.092803,1686.602691,1137.716802,1633.259988,1330.344947,1737.977716,1331.215126,1816.750847,1523.604049,1654.741874,1496.651184,1877.220892

In [21]:
# Calcular el precio maximo por trimestre para cada ticket
max_trimestre_ticket = df_stockdata.groupby(['year', 'quarter'])[ticker_cols].max()
max_trimestre_ticket.head()

                      MCD         SBUX         GOOG         AMZN         MSFT  \
year quarter
2016 1        1789.471270  2853.621490  2204.022007  1808.015698  1312.876705
     2        2323.566965  2730.681594   798.576545  2451.920443  2129.366311
     3        2791.202027  2430.117527  2196.930350  2618.237953  2665.021845
     4        2957.381849  2586.369832  2026.242576  2292.010258  1269.710679
2017 1        2776.340046  2694.417472  2664.646680  2346.230371  2457.149935

                      JPM          BAC            C          MAR          HLT  \
year quarter
2016 1        2848.190046  2897.927138  2602.543153  1815.311585  2132.975556
     2        2195.151289  2491.350402  1089.557380  2909.666344  2332.144485
     3        1540.454953  2725.472428  2148.337018  2428.097261  2691.391161
     4        2192.802555  1840.406072  1907.948317  2830.441821  1621.250812
2017 1        1678.946410  1946.163188  2698.705940  2082.085082  2694.730801

                      RCL            V           MA         PYPL
year quarter
2016 1        2062.172089  2910.632261  2502.354643  1557.276282
     2        2820.311856  2687.637231  1805.762937  2961.054202
     3        2319.772524  1496.572921  1582.516503  1299.796825
     4        2727.549681  2510.848412  1109.979919  2916.192786
2017 1        2812.088067  2000.600254  1042.967063  1067.152437

In [3]:

import pandas as pd
# URL del archivo CSV
url = 'https://raw.githubusercontent.com/brunobobadilla06/Bruno-CienciaDeDatos/refs/heads/main/stocks_data.csv'
df_stockdata = pd.read_csv(url)

df_stockdata['formatted_date'] = pd.to_datetime(df_stockdata['formatted_date'])
condicion_fecha = df_stockdata['formatted_date'] >= pd.Timestamp('2016-03-01')
df_desde_marzo = df_stockdata[condicion_fecha]
df_stockdata['year'] = df_stockdata['formatted_date'].dt.year

# Contar cuantos registros (meses) hay por año
registros_por_año = df_stockdata.groupby('year').size()
registros_por_año.head()

year
2016    12
2017    12
2018    12
2019    12
2020    12
dtype: int64

In [4]:
# Agregacion multiples con .agg()
# Aplicamos .agg() despues de agrupar por tiempo, especificando que hacer con cada columna de tickets(o las mismas operaciones para varias)
agregaciones_seleccion = {
    'GOOG': ['min', 'max', 'mean', 'std'],
    'AMZN': ['min', 'max', 'mean', 'std'],
    'MSFT': ['min', 'max', 'mean', 'std']
}
Prom_des__std_por_año = df_stockdata.groupby('year').agg(agregaciones_seleccion)
Prom_des__std_por_año.head()

            GOOG                                               AMZN  \
             min          max         mean          std         min
year
2016   46.400688  2204.022007  1149.711218   893.024299  536.456647
2017  533.393458  2919.841348  1875.463930   864.510645   79.265852
2018  246.106129  2908.828531  1665.574214  1079.441483  301.121430
2019  388.288537  2735.453738  1417.195157   845.743488   73.197657
2020  408.641327  2684.860972  1679.092803   850.246309  429.211591

                                                  MSFT               \
              max         mean         std         min          max
year
2016  2618.237953  1716.941879  635.471606  223.203231  2665.021845
2017  2863.167874  1268.562370  928.131056  105.291708  2810.379679
2018  2794.349257  1476.804462  917.373145  200.949517  2579.485873
2019  2959.950289  1987.548970  828.932323  348.300874  2910.645762
2020  2947.664492  1686.602691  950.284309  218.223662  2397.967236


             mean         std
year
2016  1268.834224  759.264403
2017  2014.165032  742.892572
2018  1300.040587  749.171740
2019  1566.252782  939.495816
2020  1137.716802  728.421921

In [9]:
# Calcular el promedio anual para todos los tickets, pero el maximo anual para AMZN
#DEFINIMOS AGREGACIONES PARA TODAS LAS COLUMNAS DE TICKETS Y UNA ESPECIFICA PARA AMZN
ticker_cols = ['MCD', 'SBUX', 'GOOG', 'AMZN', 'MSFT', 'JPM', 'BAC', 'C', 'MAR', 'HLT', 'RCL', 'V', 'MA', 'PYPL']
agg_dict = {ticket: 'mean' for ticket in ticker_cols}

agg_dict['AMZN'] = ['mean', 'max']

resumen_combinado = df_stockdata.groupby('year').agg(agg_dict)
resumen_combinado.head()

              MCD         SBUX         GOOG         AMZN               \
             mean         mean         mean         mean          max
year
2016  1533.838973  1287.386985  1149.711218  1716.941879  2618.237953
2017  1804.930096  1492.415311  1875.463930  1268.562370  2863.167874
2018  1614.790399  1600.832842  1665.574214  1476.804462  2794.349257
2019  1562.967591  1410.188407  1417.195157  1987.548970  2959.950289
2020  1159.219380  1745.392282  1679.092803  1686.602691  2947.664492

             MSFT          JPM          BAC            C          MAR  \
             mean         mean         mean         mean         mean
year
2016  1268.834224  1285.097300  1712.806759  1367.539270  1617.312686
2017  2014.165032  1343.280802  1436.322995  1643.784516  1456.501425
2018  1300.040587  1736.936332  1177.508790  1813.186731  1207.500218
2019  1566.252782  1420.429739  1464.899190  1410.024538  1763.043543
2020  1137.716802  1633.259988  1330.344947  1737.977716  1331.215126

              HLT          RCL            V           MA         PYPL
             mean         mean         mean         mean         mean
year
2016  1504.196184  1500.033476  1756.132206  1026.738754  1479.779124
2017  1824.998160  1421.171947  1546.111674  1234.712169  1112.974309
2018  1816.055636  1129.492182  1640.062840  1804.624401  1875.359713
2019  1378.920654   904.334448  1074.505580  1213.750519  1658.291227
2020  1816.750847  1523.604049  1654.741874  1496.651184  1877.220892

In [20]:
url = 'https://raw.githubusercontent.com/brunobobadilla06/Bruno-CienciaDeDatos/refs/heads/main/stocks_data.csv'
df_stockdata = pd.read_csv(url)

df_stockdata['formatted_date'] = pd.to_datetime(df_stockdata['formatted_date'])
condicion_fecha = df_stockdata['formatted_date'] >= pd.Timestamp('2016-03-01')
df_desde_marzo = df_stockdata[condicion_fecha]

df_stockdata['year'] = df_stockdata['formatted_date'].dt.year
df_stockdata['month'] = df_stockdata['formatted_date'].dt.month
df_stockdata['quarter'] = df_stockdata['formatted_date'].dt.quarter

#   Calcular el precio promedio trimestral de JPM y BAC solo para el año 2016
df_filtrado_2016 = df_stockdata[df_stockdata['year'] == 2016]
promedio_trim_bancos_2016 = df_filtrado_2016.groupby('quarter')[['JPM', 'BAC']].mean()
promedio_trim_bancos_2016

                 JPM          BAC
quarter
1        1412.148106  1649.212855
2        1535.219979  2155.250954
3        1185.682118  1930.522521
4        1007.338995  1116.240706

In [1]:
# ejemplo rapido de como tranformar a formato
df_largo = pd.melt(df_stockdata,
                   id_vars=['formatted_date', 'year', 'month', 'quarter'],
                   value_vars = ticker_cols,
                   var_name = 'ticker',
                   value_name = 'price'
                   )
df_largo.head()

NameError: name 'pd' is not defined

In [1]:
# Aplicando funciones a los datos como apply, map
# a.map() se utiliza para sustituir cada valor en una serie por otro valor, funciona exclusivamete con series o a columna de dataframe
# se le puede pasar un diccionario o una funcion para realizar mapeo
# tranforma los valores de una serie
import pandas as pd
import numpy as np
df = pd.DataFrame({'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla'],
                   'Poblacion': [3305408, 1636732, 791413, 688592]})
# Mapeo usando un diccionario
mapeo_ciudades = {'Madrid': 1, 'Barcelona': 2, 'Valencia': 3, 'Sevilla': 4}
df['Codigo_Ciudad'] = df['Ciudad'].map(mapeo_ciudades)
print(df)

      Ciudad  Poblacion  Codigo_Ciudad
0     Madrid    3305408              1
1  Barcelona    1636732              2
2   Valencia     791413              3
3    Sevilla     688592              4

In [3]:
df_numerico = df[['Poblacion', 'Codigo_Ciudad']]

def formato_miles(valor):
  return f'{valor: ,}'

df_formateado = df_numerico.map(formato_miles)

df_formateado

    Poblacion Codigo_Ciudad
0   3,305,408             1
1   1,636,732             2
2     791,413             3
3     688,592             4

In [4]:
#Apply(): Operaciones sobre filas o columnas
# El mewtodo apply() es mas versatil y puede operar tanto en DataFrame como en series. Cuando se usa en un dataframe puede aplicar una funcion a lo largode un eje (filas o columna)

# Aplicar una funcion a auna columna serie
def categorizar_poblacion(poblacion):
  if poblacion > 2000000:
    return 'Muy grande'
  elif poblacion > 1000000:
    return 'Grande'
  else:
    return 'Mediana'
df['Categoria_Poblacion'] = df['Poblacion'].apply(categorizar_poblacion)
df

      Ciudad  Poblacion  Codigo_Ciudad Categoria_Poblacion
0     Madrid    3305408              1          Muy grande
1  Barcelona    1636732              2              Grande
2   Valencia     791413              3             Mediana
3    Sevilla     688592              4             Mediana

In [5]:
# Aplicar una funcion a travez de las filas (axis=1)
def info_ciudad(fila):
  return f'{fila["Ciudad"]} tiene el codigo {fila["Codigo_Ciudad"]}'
df['Info_Ciudad'] = df.apply(info_ciudad, axis=1)
df

,Ciudad,Poblacion,Codigo_Ciudad,Categoria_Poblacion,Info_Ciudad
0,Madrid,3305408,1,Muy grande,Madrid tiene el codigo 1
1,Barcelona,1636732,2,Grande,Barcelona tiene el codigo 2
2,Valencia,791413,3,Mediana,Valencia tiene el codigo 3
3,Sevilla,688592,4,Mediana,Sevilla tiene el codigo 4